### ISSUE TITLE
CreditCardAutofill triggers an exception on every document mutation

### ISSUE THREAD

**Issue by Zixxer636** [mozilla-mobile/firefox-ios#13953]
Our website was flooding our webserver with error messages "Script error.". After attaching the iOS Firefox to the Safari debugger we found that on every document body mutation an exception was triggered. (And we did this on every frame).

`Exception with thrown value: TypeError: this.findForms is not a function. (In 'this.findForms(e[t].addedNodes)', 'this.findForms' is undefined)`

https://github.com/mozilla-mobile/firefox-ios/blob/9bff9750c7055df060c31dd80dfcc396c0072c44/Client/Frontend/UserContent/UserScripts/AllFrames/AtDocumentStart/CreditCardHelper.js#L18-L22

## Steps to reproduce
It seems like going to http://www.twitter.com/  and adding a div to the body already triggers it.

`document.body.appendChild(document.createElement("div"))`

### Expected behavior
No error

### Actual behavior
The exception is thrown

### Device & build information
* Device: 16.4 
* Build version: 114 

![Screenshot 2023-04-13 at 13 34 52](https://user-images.githubusercontent.com/29260512/231746728-33131983-e935-4113-be7e-641335561714.png)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-6186)

**Comment by jetelain** [comment]
Hi,

We have reproduced on our websites, and was leading to infinite recursion (and then webkit process crash).
We had a script that shows to user a message when a script error is intercepted by window.onerror, Since the display of the error is mutating the DOM, it was leading to an other call to the MutationObserver, etc.

Minimalist code to reproduce (with jQuery)
```js
window.onerror = function(){
$('body').prepend($('<div></div>').text('An error has occured, the action might have failed.'));
}
```

As a workaround, we have disabled error management.

**Comment by jetelain** [comment]
Bug was introduced by #12787

**Comment by lmarceau** [comment]
Thank you for raising this issue! We'll have a look to fix it 🙏

**Comment by data-sync-user** [comment]
➤ Nishant Bhasin commented:

I added a feature flag so no script should be injected until the feature is out of development.

**Comment by nbhasin2** [comment]
cc @issammani for future production iterations

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Nishant Bhasin could you please add some details for the QA to know what we have to test for this? Also Fix_version  should be added in order for the QA team to prioritize the validation.

**Comment by nbhasin2** [comment]
Q. @issammani if this is fixed by script updates then is there a specific website that our we can use for testing?

**Comment by issammani** [comment]
> Q. @issammani if this is fixed by script updates then is there a specific website that our we can use for testing?

This was fixed a long time ago in the initial phase. We don't use mutation observers anymore. So we won't be able to reproduce this.

**Comment by issammani** [comment]
@nbhasin2 I think this has been fixed for over a year ( I wasn't familiar with the jira flow then ). The fix version should be the first ever version we shipped credit card autofill in.

**Comment by nbhasin2** [comment]
@issammani that's my guess to but I honestly don't remember the sha for it. However I am okay to close this ticket but if someone were to test this, is there a specific website they can visit?

**Comment by data-sync-user** [comment]
➤ Alina Moldovan commented:

Closing the issue based on the above comments
