### ISSUE TITLE
FXIOS-1623 ⁃ Beta Build: Push out a beta build with AppServices (v74.0.1)

### ISSUE THREAD

**Issue by data-sync-user** [mozilla-mobile/firefox-ios#8195]
Currently we are on v69.0.0 of Application Services and we should push out a new beta with v74.0.1 as that has changes like nimbus and also update glean in this process. 

Letting A~S be in beta will capture any major issues that we might encounter if we just push it to production directly.

**A~S:** https://github.com/mozilla/application-services/releases/tag/v74.0.1

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FXIOS-2794)

**Comment by isabelrios** [comment]
In case this helps, as you can see in the created PR, the app is not building with that AppServices version v74.0.1:
https://github.com/mozilla-mobile/firefox-ios/pull/8130/files
Compilation Error: 
/Users/vagrant/git/RustFxA/RustFirefoxAccounts.swift:234:64: cannot use optional chaining on non-optional value of type 'String'
        let avatarUrl = accountManager.accountProfile()?.avatar?.url
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
❌  /Users/vagrant/git/RustFxA/RustFirefoxAccounts.swift:234:66: value of type 'String' has no member 'url'
        let avatarUrl = accountManager.accountProfile()?.avatar?.url
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~
❌  /Users/vagrant/git/RustFxA/RustFirefoxAccounts.swift:316:35: cannot use optional chaining on non-optional value of type 'String'
        avatarUrl = profile.avatar?.url
                    ~~~~~~~~~~~~~~^
❌  /Users/vagrant/git/RustFxA/RustFirefoxAccounts.swift:316:37: value of type 'String' has no member 'url'
